export default {
    PHOTO_DELETED_FULFILED: 'PHOTO_DELETED_FULFILED',
    PHOTO_DELETED_REJECTED: 'PHOTO_DELETED_REJECTED',
    FILTER_PHOTOS: 'FILTER_PHOTOS',
    FETCH_PHOTOS_REJECTED: 'FETCH_PHOTOS_REJECTED',
    FETCH_PHOTOS_FULFILLED: 'FETCH_PHOTOS_FULFILLED'
};
